#!/bin/bash
ga
if [ -d ../common ]; then
	cd frameworks_gaia/base/core/java/android/view/accessibility
else
	cd frameworks/base/core/java/android/view/accessibility
fi

if [ $# -gt 1 ]; then
	echo $@
	$@
fi
