#!/bin/bash
ga
if [ -d ../common ]; then
	cd frameworks_gaia/base/core/java/android/accessibilityservice
else
	cd frameworks/base/core/java/android/accessibilityservice
fi
if [ $# -gt 1 ]; then
	echo $@
	$@
fi
