#!/bin/bash

if [ "$OUT" == "" ]; then
	OUT_SYSTEM="/home/quaker/workspace/device/out/target/product/$BOARD/system"
else
	OUT_SYSTEM="$OUT/system"
fi

if [ $# -lt 1 ]; then
	echo "	adbp [-e] [ts] <lib|bin|pkg|mod> <filename>"
	echo "		ex: adbp lib evas"
	echo "		ex: adbp bin execme"
	echo "		ex: adbp pkg app_ex1"
	exit 0
fi

if [ "$1" == "e" ]; then
	gedit /home/quaker/bashscript/adbp &
	exit 0
fi

if [ "$1" == "-e" ]; then
	EMU="-e"
	shift
fi

adb $EMU "wait-for-device"
adb remount
case $1 in
	"lib")
		echo From: $OUT_SYSTEM/lib/lib$2.so;
		echo  To : system/lib;
		#adb $EMU push $OUT_SYSTEM/lib/lib$2.so system/lib;;
		echo $OUT_SYSTEM/lib/lib$2.so | awk '
{
	split( $0, A, " " )
	for(i = 1 ; i <= NF ; i++) {
		print "echo \"adb " emu " push " A[i] " system/lib\""
		print "adb " emu " push " A[i] " system/lib"
	}
}
' > /tmp/push_list;
		source /tmp/push_list;
		rm /tmp/push_list;;
	"bin")
		echo From: $OUT_SYSTEM/bin/$2;
		echo  To : system/bin;
		echo adb $EMU push "$OUT_SYSTEM/bin/$2" system/bin;
		eval adb $EMU push "$OUT_SYSTEM/bin/$2" system/bin ;;
	"mod")
		echo From: $OUT_SYSTEM/lib/evas/modules/engines/$2/$3;
		echo  To : system/lib/evas/modules/engines/$2;
		eval adb $EMU push "$OUT_SYSTEM/lib/evas/modules/engines/$2/$3" system/lib/evas/modules/engines/$2 ;;
	"pkg")
		echo From: $OUT_SYSTEM/app/$2.pkg;
		echo  To : system/app;
		echo adb $EMU install -r $OUT_SYSTEM/app/$2.pkg ;
		eval adb $EMU install -r $OUT_SYSTEM/app/$2.pkg ;;
	"apk")
		echo From: $OUT_SYSTEM/app/$2.apk;
		echo  To : system/app;
		echo adb $EMU install -r $OUT_SYSTEM/app/$2.apk ;
		eval adb $EMU install -r $OUT_SYSTEM/app/$2.apk ;;
	*)
		echo adb push $OUT_SYSTEM/$2/$3 system/bin/$2;
		eval adb push $OUT_SYSTEM/$2/$3 system/bin/$2 ;;
esac
