#!/bin/bash
if [ "$1" == "e" ]; then
	gedit ~/bashscript/adbr &
	exit
fi
if [ "$1" == "-e" -o "$1" == "-d" ]; then
	echo "adb $1 reboot $2"
	adb $1 reboot $2
else
	echo "adb reboot $@"
	adb reboot $@
fi
