#!/bin/bash
# for converting motion to gsr script
grep -e Pointer -e "Dispatch Motion.*action=[01]\]" $1| sed 's/.*action=\(0\).*/\1/g' | sed 's/.*action=\(1\).*//g' | sed 's/.*x=\([0-9\.]*\), y=\([0-9\.]*\).*/\1 \2/g' | awk '{RS="0\n"} {print $1 " " $2 " " $3 " " $4 "\n"}'
