#!/bin/bash
#export TARGET_BUILD_TYPE=debug

#default
INTERNAL_VALID_VARIANTS="userdebug"
TARGET_PRODUCT="htc_songshan"

MAKETHREAD=""
ERR=0
#please enter abslute path
#To the best, edit .bashrc expand the both lines.
GAIA_PATH="/home/quaker/workspace/gaia/common"
#if [ -f /tmp/glink/build/envsetup.sh ]; then
#	GAIA_PATH="/tmp/glink"
#fi

pushd . >/dev/null
pushd . >/dev/null

# find local gaia path
while [ $PWD != "/" ];
do
	if [ -f "build/envsetup.sh" ]; then
		break
	fi
	cd ..
done
if [ -f "build/envsetup.sh" ]; then
	GAIA_PATH=$PWD
	echo "Gaia path: $GAIA_PATH"
fi
GLOG="$GAIA_PATH/out/bG_L.log"
GERR="$GAIA_PATH/out/bG_E.log"
if [ ! -d $GAIA_PATH/out ]; then
	mkdir -p $GAIA_PATH/out
fi

v1=$1
v2=$2
v3=$3
v4=$4

for a in $1 $2 $3 $4 $5 $6
do
	case $a in
	"e")
		gedit ~/bashscript/bG &
		exit 0;;
	"edit")
		gedit ~/bashscript/bG &
		exit 0;;
	"editme")
		gedit ~/bashscript/bG &
		exit 0;;
	"vlog")
		gvim $GLOG
		exit 0;;
	"log")
		grep -e "No rule" -e " error" -e " Err" -e "\*\*\*" \
			-e "undefined reference" -e "定義" -e "參考" -e "找不到" \
			-e "note:" $GLOG | awk -v gaia_path="$GAIA_PATH" '
			{
				where = match($0, /^frameworks/)
				if (where != 0)
					print gaia_path "/" $0
				else
					print $0
			}
			'> $GERR
		gedit $GLOG &
		exit 0;;
	"verr")
		gvim $GERR
		exit 0;;
	"err")
		gedit $GERR &
		exit 0;;
	"mod")
		v7=$v3;;
	-j*)
		echo "** $a **";
		MAKETHREAD=$a;;
	"mm")
		v3="mm";
		MAKETHREAD="-j3";;
	"mmm")
		v3="mmm";
		MAKETHREAD="-j3";;
	"dry")
		echo "*** Dry mode ***";
		v4="dry";;
	esac
done

if [ "$1" == "" ]; then
	echo "buildGaia [ss|ts [c|u|mod MOD]]  [mm] [-jXX]"
	echo "buildGaia [log|vlog]"
	echo "	ss: songshan	ts:  tianshan"
	echo "	c:  clean	u:   userdebug (default)"
	echo "  mod: MOD is your specified module"
	echo "	mm: mm  	dry: dry mode"
	echo "	-jXX: XX is number of threads"
	echo "  log: use gedit	vlog: use gvim"
	read -p "Run default: buildGaia ss u (Y/N): " yn
	[ "$yn" != "Y" -a "$yn" != "y" ] && exit 0
	v1="ss"
	v2="ts"
	v3=""
fi

case $v1 in
	"ss")
		echo "songshan";
		export TARGET_PRODUCT=htc_songshan;;

	"ts")
		echo "tianshan";
		export TARGET_PRODUCT=htc_tianshan;;

	"br")
		echo "tianshan";
		export TARGET_PRODUCT=htc_bravo;;

	* ) 
		echo "songshan";
		export TARGET_PRODUCT=htc_songshan;;
esac

case $v2 in
	"c" | "clean" )
		echo "clean";
		export INTERNAL_VALID_VARIANTS=clean;;

	"u" | "userdebug" )
		echo "userdebug";
		[ "$MAKETHREAD" == "" ] && export MAKETHREAD="-j10";
		export INTERNAL_VALID_VARIANTS=userdebug;;

	"mod" )
		echo "mod=$v7";
		export INTERNAL_VALID_VARIANTS=$v7;;

	* ) 
		echo "userdebug";
		[ "$MAKETHREAD" == "" ] && export MAKETHREAD="-j10";
		export INTERNAL_VALID_VARIANTS=userdebug;;
esac

if [ $ERR == 0 ]; then
	cd $GAIA_PATH
	. build/envsetup.sh


	echo ""
	BUILDERR=0;
	if [ "$v3" == "mm" -o "$v3" == "mmm" ]; then
		popd >/dev/null
		echo "$PWD/$v3 $MAKETHREAD PRODUCT-$TARGET_PRODUCT-$INTERNAL_VALID_VARIANTS  2>&1 | tee $GLOG"
		if [ "$v4" != "dry" ]; then
			$v3 $MAKETHREAD "PRODUCT-$TARGET_PRODUCT-$INTERNAL_VALID_VARIANTS" 2>&1 | tee $GLOG
			# | grep --color=auto -e Target -e "No rule" -e " error" -e " Err" -e "\*\*\*" -e "undefined reference" -e "定義" -e "參考" -e "找不到" -e "note:"
			if [ $? -ne 0 ]; then
				BUILDERR=1;
			fi
		fi
	else
		echo "make $MAKETHREAD PRODUCT-$TARGET_PRODUCT-$INTERNAL_VALID_VARIANTS 2>&1 | tee $GLOG"
		if [ "$v4" != "dry" ]; then
			make $MAKETHREAD "PRODUCT-$TARGET_PRODUCT-$INTERNAL_VALID_VARIANTS" 2>&1 | tee $GLOG
			# | grep --color=auto -e Target -e "No rule" -e " error" -e " Err" -e "\*\*\*" -e "undefined reference" -e "定義" -e "參考" -e "找不到" -e "note:"
			popd >/dev/null
			if [ $? -ne 0 ]; then
				$BUILDERR = 1;
			fi
		fi
	fi

	grep -A 3 -B 3 -e "No rule" -e " error" -e " Err" -e "\*\*\*" \
		-e "undefined reference" -e "定義" -e "參考" -e "找不到" \
		$GLOG | awk -v gaia_path="$GAIA_PATH" '
		{
			where = match($0, /^frameworks/)
			if (where != 0)
				print  "/tmp/glink/" $0
			else
				print $0
		}
		'> $GERR
#	if [ $BUILDERR -eq 1 ]; then
#		grep --color=auto -e "No rule" -e " error" -e " Err" -e "\*\*\*" \
#			-e "undefined reference" -e "定義" -e "參考" -e "找不到" \
#			-e "note:" $GERR
#	else
#		echo ""
#		echo "Build pass"
#	fi
else
	echo ""
	echo "False command.  Do nothing."
fi
popd >/dev/null

#			/^frameworks/ { print "/home/quaker/workspace/gaia/" $0 }
#			/{ print $0 }

