#!/bin/bash
TIME_BEGIN=$(date)
echo "Build begin at $TIME_BEGIN"
#export LANG=en_US

if [ "$TARGET_BUILD_VARIANT" == "" ]; then
	echo "can't find \$TARGET_BUILD_VARIANT"
else
if [ "$TOP" != "" ]; then
	export USE_CCACHE=1
	#let each build folder use different .ccache
	if [ "$TARGET_PRODUCT" != "" ]; then
	    CCACHE_DIR=$(ccdir)
	    if [ ! -d $CCACHE_DIR ]; then
	        ccdir -m
	    fi
	    echo "CCACHE_DIR=$CCACHE_DIR"
		echo ""
		echo ""

	    ccache -M 50G
	    mm $@
	else
	    echo 'Need $TARGET_BUILD_VARIANT'
	fi
fi
fi

echo "Build Time: $TIME_BEGIN ~ $(date)"

