#!/bin/bash
source ~/bashscript/env.sh
echo Finding git directories may take time...
for gitpath in $(find . -wholename ./.repo -prune -o -name .git);
do
    echo $gitpath
    if [ "$gitpath" != "" -a -d "$gitpath" ]; then
	    pushd . > /dev/null
	    cd $gitpath/..
	    pwd
	    $@
	    if [ $? -ne 0 ]; then
	        echo -e "\e[91m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ \e[0m"
	    fi
	    popd > /dev/null
    fi
done
