#!/bin/bash
ga
FRAMEWORKS_PATH=
if [ -d ../common ]; then
	FRAMEWORKS_PATH=frameworks_gaia
else
	FRAMEWORKS_PATH=frameworks
fi


if [ "$1" == "1" ]; then
	cd $FRAMEWORKS_PATH/base/graphics/java/android/graphics/
	shift
else
	cd $FRAMEWORKS_PATH/base/graphics/java/android/graphics/
fi
if [ $# -gt 1 ]; then
	echo $@
	$@
fi

