#!/bin/bash
if [ "$1" == "e" ]; then
	gedit ~/bashscript/mypush &
	exit
fi

if [ "$1" == "ts" ]; then
	TS="ts"
	shift
fi

if [ "$1" == "-e" ]; then
	DEVICE="-e"
	shift
fi

if [ $# -ne 0 ]; then
	if [ $(( $1 & 1 )) -eq 1 ]; then 
		echo ==== build Wallpaper ====
		cd ~/workspace/gaia/frameworks/base/core/java/android/service/wallpaper
		bG $TS mm

		echo ==== build IWallpaper ====
		cd ~/workspace/gaia/frameworks/base/core/java/android/service/iwallpaper
		bG $TS mm
	fi
	if [ $(( $1 & 2 )) -eq 2 ]; then
		echo ==== build Image Wallpaper ====
		cd ~/workspace/gaia/frameworks/base/core/java/com/android/internal/service/wallpaper/imagewp
		bG $TS mm

		echo ==== build HTC Color Blur ====
		cd external/wpcolorblur
		bG $TS mm
	fi
	if [ $(( $1 & 4 )) -eq 4 ]; then
		echo ==== build WpMS ====
		cd ~/workspace/gaia/frameworks/base/cmds/app_process/examples/wms
		bG $TS mm

		echo ==== build WpM ====
		cd ~/workspace/gaia/frameworks/base/cmds/app_process/examples/wm
		bG $TS mm

		echo ==== build WpMS exec ====
		cd ~/workspace/gaia/frameworks/base/cmds/app_process/examples/wms_bin
		bG $TS mm
		
		echo ==== build WpM exec ====
		cd ~/workspace/gaia/frameworks/base/cmds/app_process/examples/wm_bin
		bG $TS mm
	fi
	if [ $(( $1 & 8 )) -eq 8 ]; then
		echo ==== build Launcher ====
		cd ~/workspace/gaia/frameworks/base/cmds/app_process/examples/launcher
		bG $TS mm
	fi
	if [ $(( $1 & 16 )) -eq 16 ]; then
		echo ==== build Video Wallpaper ====
		cd ~/workspace/gaia/frameworks/base/core/java/com/android/internal/service/wallpaper/VideoWallpaper
		bG $TS mm

		echo ==== build PhotoRiver Wallpaper ====
		cd ~/workspace/gaia/frameworks/base/core/java/com/android/internal/service/wallpaper/PhotoRiver
		bG $TS mm
		
		~/bashscript/adbps $TS $DEVICE lib videowallpaper
		~/bashscript/adbps $TS $DEVICE lib PhotoRiverWP
	fi
	if [ $(( $1 & 32 )) -eq 32 ]; then
		echo ==== build Resources ====
		cd ~/workspace/gaia/frameworks/base/core/java/android/content/res
		bG $TS mm

		echo "==== build test ===="
		cd ~/workspace/gaia/frameworks/base/core/java/android/content/res/drawable/test/test1
		bG $TS mm
		
		~/bashscript/adbps $TS $DEVICE lib res
		~/bashscript/adbps $TS $DEVICE bin dt
		exit 0
	fi
	if [ $(( $1 & 64 )) -eq 64 ]; then
		echo ==== build Utils ====
		cd ~/workspace/gaia/frameworks/base/core/java/android/content/res
		bG $TS mm

		echo ==== build PhotoRiver Wallpaper ====
		cd ~/workspace/gaia/frameworks/base/core/java/android/content/res/test/test1
		bG $TS mm
		
		~/bashscript/adbps $TS $DEVICE lib res
		~/bashscript/adbps $TS $DEVICE bin dt
		exit 0
	fi
	echo =====: Build complete :=====
fi

~/bashscript/adbps $TS $DEVICE lib iwp
~/bashscript/adbps $TS $DEVICE lib wpm
~/bashscript/adbps $TS $DEVICE lib launcher
~/bashscript/adbps $TS $DEVICE lib wallpaper
~/bashscript/adbps $TS $DEVICE bin wpms
~/bashscript/adbps $TS $DEVICE lib wpms
~/bashscript/adbps $TS $DEVICE lib imagewallpaper
~/bashscript/adbps $TS $DEVICE lib sensewp
~/bashscript/adbps $TS $DEVICE bin wpm


