#!/bin/bash
qa > /dev/null

if [ "$1" != "" -a -d "out/target/product/$1" ]; then
    OUT_OUT="out/target/product/$1"
	shift
elif [ -d "$ANDROID_PRODUCT_OUT" ]; then
	OUT_OUT="$ANDROID_PRODUCT_OUT"
else
    getout
#	type get_abs_build_var > /dev/null
#	if [ $? -eq 0 ]; then
#		OUT_OUT=`get_abs_build_var PRODUCT_OUT`
#	fi
fi

if [ -d "$OUT_OUT" ]; then
	cd $OUT_OUT

	# Run command
	if [ $# -gt 1 ]; then
		echo "$@"
		$@
	fi
else
	echo "cant find out folder"
	popd > /dev/null
fi

