#!/bin/bash
pushd . >/dev/null
#I dont need croot any more.
#type croot &>/dev/null && croot &>/dev/null
#if [ $? -ne 0 ]; then
SUCCESS_CHANGE=0
CURRENT_SOURCE=

	# find local gaia path
	while [ $PWD != "/" ];
	do
		if [ -f "kernel_setup.sh" ]; then
			break
		fi
		cd ..
	done
	if [ -f "kernel_setup.sh" ]; then
		SUCCESS_CHANGE=1
		export QUATTRO_KERNEL_PATH=$PWD

		echo "QUATTRO_KERNEL path: $QUATTRO_KERNEL_PATH"
		if [ $# -gt 1 ]; then
			echo $@
			$@
		fi
	else
		QPATH="/home/quaker/workspace/quattro-kernel"
		if [ -d $QPATH ]; then
			cd $QPATH
			SUCCESS_CHANGE=1

			export QUATTRO_KERNEL_PATH=$QPATH
			QPATH=

			echo "QUATTRO_KERNEL path: $QUATTRO_KERNEL_PATH"
			if [ $# -gt 1 ]; then
				echo $@
				$@
			fi
		else
			popd > /dev/null
		fi
	fi

	if [ $SUCCESS_CHANGE -eq 1 ]; then
#		if [ ! "$CURRENT_SOURCE" == "QK" ]; then
#			#cscope
#		fi
		export CURRENT_SOURCE=QK
	fi

#fi
