#!/bin/bash
ga
FRAMEWORKS_PATH=
if [ -d ../common ]; then
	FRAMEWORKS_PATH=frameworks_gaia
else
	FRAMEWORKS_PATH=frameworks
fi
if [ "$1" != "" ]; then
	echo $1;
	case $1 in
		"1")
			echo hi 1;
			cd $FRAMEWORKS_PATH/base/core/java/com/android/internal/service/wallpaper;;
		"2")
			echo hi 2;
			cd packages/apps/MultiColorBlur;;
		"3")
			echo hi 3
			if [ "$2" != "" ]; then
				cd packages/apps/CubeWallpaper/src/com/example/android/livecubes/
			else
				cd packages/apps/CubeWallpaper
			fi;;
		*)
			echo "What\'s that?";;
	esac
	shift
else
	cd $FRAMEWORKS_PATH/base/core/java/android/service/wallpaper
fi

if [ $# -gt 1 ]; then
	echo $@
	$@
fi
