#!/bin/bash
ga
if [ -d ../common ]; then
	cd frameworks_gaia/base/services/java/com/android/server/wpms
else
	cd frameworks/base/services/java/com/android/server/wpms
fi
if [ $# -gt 1 ]; then
	echo $@
	$@
fi

